import { useTranslation } from 'react-i18next'

const en = {
  play: 'Play',
  pause: 'Pause',
  seek: 'Seek',
  volume: 'Volume',
  speed: 'Playback speed',
  edit: 'Edit title',
  editPoster: 'Change cover',
  rewind: 'Back 10 seconds',
  forward: 'Forward 10 seconds',
  remove: 'Remove torrent',
  removeQuestion: 'Remove this torrent from the library?',
  genre: 'Genre',
  library: 'Library',
  search: 'Search',
  menu: 'Menu',
  back: 'Back',
  close: 'Close',
  retry: 'Retry',
  downloads: 'Downloads',
  discover: 'Discover films',
  add: 'Add a torrent',
  settings: 'Server settings',
  filters: 'Filter and sort',
  all: 'All',
  sort: 'Sort A–Z',
  recent: 'Recently added',
  movie: 'Films',
  tv: 'Series',
  watch: 'Watch',
  resume: 'Continue',
  watched: 'Watched',
  unwatched: 'Not watched',
  markWatched: 'Mark as watched',
  markUnwatched: 'Mark as unwatched',
  historyError: 'Cannot load viewing history.',
  historySaveError: 'Could not save the watched status. Try the watched button again.',
  episode: 'Episode',
  episodes: 'Episodes',
  filesInTorrent: 'Files in this torrent',
  season: 'Season',
  download: 'Download ahead',
  downloadAll: 'Download all episodes',
  cancel: 'Cancel download',
  disk: 'Saved on home server',
  streaming: 'Stream online',
  downloadHint: 'Downloads are saved on your home server.',
  queued: 'Queued',
  downloading: 'Downloading',
  completed: 'Saved',
  failed: 'Download failed',
  cancelled: 'Cancelled',
  missing: 'File unavailable',
  not_downloaded: 'Not saved',
  partial: 'Partly saved',
  unavailable: 'Storage unavailable',
  details: 'File details',
  format: 'Format',
  quality: 'Quality',
  fileSize: 'File size',
  source: 'Playback source',
  fullPath: 'Full file path',
  advanced: 'Advanced torrent controls',
  version: 'Version',
  empty: 'Your library starts here',
  emptyText: 'Find a film or add a torrent link.',
  offline: 'Cannot connect to the server',
  offlineText: 'Check the connection and your server address.',
  noResults: 'No matches for this filter',
  clear: 'Clear filters',
  noDownloads: 'No downloads yet',
  loading: 'Loading…',
  updating: 'Updating…',
  loadingFiles: 'Getting the file list…',
  file: 'File',
  preparingDownload: 'Preparing file details',
  queueHint: 'Queued. The download will start automatically after the current file.',
  downloadQueueHint: 'One file downloads at a time. Other selections wait in the queue.',
  noFiles: 'No playable files are available yet.',
  noOverview: 'No description available.',
  noTitle: 'This title is no longer in the library.',
  storageError: 'Cannot check storage. The online stream remains available.',
  tracks: 'Audio and subtitles',
  audio: 'Audio language',
  subtitles: 'Subtitles',
  off: 'Off',
  font: 'Font',
  size: 'Size',
  position: 'Position',
  sans: 'Sans serif',
  serif: 'Serif',
  mono: 'Monospace',
  bottom: 'Bottom',
  higher: 'Higher',
  middle: 'Middle',
  track: 'Track',
  noAudio: 'This browser does not expose audio track selection for this file.',
  bitmapSubtitle: 'Image subtitles · native player',
  captionError: 'Could not load subtitles. Select the track again to retry.',
  noSubtitles: 'No subtitle tracks are available to this browser.',
  playbackError: 'The video could not be played. Check the connection or open it in another player.',
  buffering: 'Waiting for video data…',
  openExternal: 'Open in VLC',
  fullscreen: 'Fullscreen',
}
const ru = {
  play: 'Воспроизвести',
  pause: 'Пауза',
  seek: 'Перемотка',
  volume: 'Громкость',
  speed: 'Скорость воспроизведения',
  edit: 'Изменить карточку',
  editPoster: 'Изменить обложку',
  rewind: 'Назад на 10 секунд',
  forward: 'Вперёд на 10 секунд',
  remove: 'Удалить торрент',
  removeQuestion: 'Удалить торрент из библиотеки?',
  genre: 'Жанр',
  library: 'Библиотека',
  search: 'Поиск',
  menu: 'Меню',
  back: 'Назад',
  close: 'Закрыть',
  retry: 'Повторить',
  downloads: 'Загрузки',
  discover: 'Подбор фильма',
  add: 'Добавить торрент',
  settings: 'Настройки сервера',
  filters: 'Фильтры и сортировка',
  all: 'Все',
  sort: 'По алфавиту',
  recent: 'Недавно добавленные',
  movie: 'Фильмы',
  tv: 'Сериалы',
  watch: 'Смотреть',
  resume: 'Продолжить',
  watched: 'Просмотрено',
  unwatched: 'Не просмотрено',
  markWatched: 'Отметить просмотренным',
  markUnwatched: 'Снять отметку просмотра',
  historyError: 'Не удалось загрузить историю просмотров.',
  historySaveError: 'Не удалось сохранить отметку просмотра. Повторите действие кнопкой отметки.',
  episode: 'Серия',
  episodes: 'Эпизоды',
  filesInTorrent: 'Файлов в раздаче',
  season: 'Сезон',
  download: 'Скачать заранее',
  downloadAll: 'Скачать все серии',
  cancel: 'Отменить загрузку',
  disk: 'Сохранено на домашнем сервере',
  streaming: 'Просмотр онлайн',
  downloadHint: 'Скачивание на диск домашнего сервера.',
  queued: 'В очереди',
  downloading: 'Скачивается',
  completed: 'Сохранено',
  failed: 'Ошибка загрузки',
  cancelled: 'Отменено',
  missing: 'Файл недоступен',
  not_downloaded: 'Не скачано',
  partial: 'Скачано частично',
  unavailable: 'Хранилище недоступно',
  details: 'Сведения о файле',
  format: 'Формат',
  quality: 'Качество',
  fileSize: 'Размер файла',
  source: 'Источник просмотра',
  fullPath: 'Полный путь к файлу',
  advanced: 'Управление торрентом',
  version: 'Версия',
  empty: 'Здесь будут ваши фильмы',
  emptyText: 'Найдите фильм или добавьте ссылку на торрент.',
  offline: 'Нет связи с сервером',
  offlineText: 'Проверьте соединение и адрес сервера.',
  noResults: 'Ничего не найдено по этому фильтру',
  clear: 'Сбросить фильтры',
  noDownloads: 'Загрузок пока нет',
  loading: 'Загрузка…',
  updating: 'Обновление…',
  loadingFiles: 'Получаем список файлов…',
  file: 'Файл',
  preparingDownload: 'Подготовка сведений о файлах',
  queueHint: 'В очереди. Скачивание начнётся автоматически после текущего файла.',
  downloadQueueHint: 'Файлы скачиваются по одному. Остальные ожидают в очереди.',
  noFiles: 'Список файлов для просмотра пока недоступен.',
  noOverview: 'Описание пока недоступно.',
  noTitle: 'Произведения больше нет в библиотеке.',
  storageError: 'Не удалось проверить хранилище. Просмотр онлайн доступен.',
  tracks: 'Звук и субтитры',
  audio: 'Язык звука',
  subtitles: 'Субтитры',
  off: 'Выключены',
  font: 'Шрифт',
  size: 'Размер',
  position: 'Положение',
  sans: 'Без засечек',
  serif: 'С засечками',
  mono: 'Моноширинный',
  bottom: 'Внизу',
  higher: 'Выше',
  middle: 'По центру',
  track: 'Дорожка',
  noAudio: 'Браузер не предоставляет выбор звуковых дорожек для этого файла.',
  bitmapSubtitle: 'Графические субтитры · нативный плеер',
  captionError: 'Не удалось загрузить субтитры. Выберите дорожку повторно.',
  noSubtitles: 'Браузеру недоступны дорожки субтитров этого файла.',
  playbackError: 'Не удалось воспроизвести видео. Проверьте соединение или откройте другой плеер.',
  buffering: 'Ожидание данных видео…',
  openExternal: 'Открыть в VLC',
  fullscreen: 'На весь экран',
}

export default function useCinemaText() {
  const { i18n } = useTranslation()
  return i18n.language?.startsWith('ru') ? ru : en
}
