import { rgba } from 'polished'

export const themeColors = {
  light: {
    app: {
      headerToggleColor: '#eff6f5',
      appSecondaryColor: '#f6faf9',
      sidebarBGColor: '#ffffff',
      sidebarFillColor: '#4c5668',
      paperColor: '#ffffff',
      borderColor: '#dde6e8',
      contentBGColor: '#fbfdfd',
      textColor: '#111827',
      mutedTextColor: '#334155',
      hoverBGColor: '#eff8f6',
      accentColor: '#008f82',
      errorTextColor: '#b42318',
      errorBGColor: '#fff1f0',
    },
    torrentCard: {
      accentCardColor: '#008f82',
      buttonBGColor: '#ffffff',
      cardPrimaryColor: '#ffffff',
      cardSecondaryColor: '#ffffff',
      borderColor: '#dfe8ea',
      titleColor: '#111827',
      statColor: '#263244',
      buttonBorderColor: '#dbe5e7',
      buttonHoverBGColor: '#eff8f6',
      detailsColor: '#008f82',
      playColor: '#008f82',
      dropColor: '#008f82',
      deleteColor: '#ff3b45',
      deleteBorderColor: '#ffd8dc',
      deleteHoverBGColor: '#fff5f6',
      deleteHoverBorderColor: '#ff9ca4',
      posterEmptyBGColor: '#f4faf9',
    },
    dialogTorrentDetailsContent: {
      posterBGColor: '#f4faf9',
      gradientStartColor: '#ffffff',
      gradientEndColor: '#fbfdfd',
      chacheSectionBGColor: '#eef7f5',
      widgetFontColor: '#fff',
      titleFontColor: '#111827',
      subNameFontColor: '#667085',
      torrentFilesSectionBGColor: '#fbfdfd',
      borderColor: '#dfe8ea',
      progressTrackColor: '#eee',
      progressBGColor: '#fff',
    },
    detailedView: {
      gradientStartColor: '#ffffff',
      gradientEndColor: '#fbfdfd',
      cacheSectionBGColor: '#fff',
    },
    addDialog: {
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      fontColor: '#000',
      notificationErrorBGColor: '#cda184',
      notificationSuccessBGColor: '#88cdaa',
      languageSwitchBGColor: '#74c39c',
      languageSwitchFontColor: '#e4f6ed',
      posterBGColor: '#74c39c',
    },
    torrentFunctions: {
      fontColor: '#000',
    },
    table: {
      defaultPrimaryColor: '#009879',
      defaultSecondaryColor: '#00a383',
      defaultTertiaryColor: '#03aa89',
      borderColor: '#dfe8ea',
      defaultRowColor: '#ffffff',
      viewedRowColor: '#f1f5f4',
      hoverRowColor: '#f8fbfa',
      textColor: '#111827',
      buttonBorderColor: '#cfdde0',
      buttonTextColor: '#008f82',
      buttonBGColor: '#ffffff',
      buttonHoverBGColor: '#eff8f6',
      buttonHoverBorderColor: '#008f82',
      headerBGColor: '#dff5f1',
      headerTextColor: '#075e56',
      mutedTextColor: '#526071',
      primaryButtonBGColor: '#00796f',
      primaryButtonTextColor: '#ffffff',
      offlineActionBGColor: '#edf8f6',
      dangerTextColor: '#b42318',
    },
    settingsDialog: {
      contentBG: '#fbfdfd',
      footerBG: '#ffffff',
    },
  },
  dark: {
    app: {
      headerToggleColor: '#071d2d',
      appSecondaryColor: '#061421',
      sidebarBGColor: '#071421',
      sidebarFillColor: '#9eb1c3',
      paperColor: '#0b1b2a',
      borderColor: '#17344d',
      contentBGColor: '#071421',
      textColor: '#e8f2fb',
      mutedTextColor: '#a4b7c9',
      hoverBGColor: '#0e283d',
      accentColor: '#23d9bd',
      errorTextColor: '#ff9c9c',
      errorBGColor: '#301524',
    },
    torrentCard: {
      accentCardColor: '#23d9bd',
      buttonBGColor: '#0a2133',
      cardPrimaryColor: '#0a1e2f',
      cardSecondaryColor: 'transparent',
      borderColor: '#15314a',
      titleColor: '#e8f2fb',
      statColor: '#c8d7e5',
      buttonBorderColor: '#24608c',
      buttonHoverBGColor: '#0e2d43',
      detailsColor: '#58a6ff',
      playColor: '#23d9bd',
      dropColor: '#22d3ee',
      deleteColor: '#ff3b52',
      deleteBorderColor: '#b7374c',
      deleteHoverBGColor: '#301524',
      deleteHoverBorderColor: '#ff5b70',
      posterEmptyBGColor: '#0e283d',
    },
    dialogTorrentDetailsContent: {
      posterBGColor: '#0e283d',
      gradientStartColor: '#0a1e2f',
      gradientEndColor: '#071421',
      chacheSectionBGColor: '#0b2639',
      widgetFontColor: '#e8f2fb',
      titleFontColor: '#e8f2fb',
      subNameFontColor: '#9eb1c3',
      torrentFilesSectionBGColor: '#071421',
      borderColor: '#17344d',
      progressTrackColor: '#123047',
      progressBGColor: '#081a29',
    },
    detailedView: {
      gradientStartColor: '#0a1e2f',
      gradientEndColor: '#071421',
      cacheSectionBGColor: '#0b2639',
    },
    addDialog: {
      gradientStartColor: '#656f76',
      gradientEndColor: '#545a5e',
      fontColor: '#fff',
      notificationErrorBGColor: '#c82e3f',
      notificationSuccessBGColor: '#323637',
      languageSwitchBGColor: '#545a5e',
      languageSwitchFontColor: '#dee3e5',
      posterBGColor: '#dee3e5',
    },
    torrentFunctions: {
      fontColor: '#f1eff3',
    },
    table: {
      defaultPrimaryColor: '#009879',
      defaultSecondaryColor: '#0c3349',
      defaultTertiaryColor: '#0d2a3f',
      borderColor: '#17344d',
      defaultRowColor: '#081a29',
      viewedRowColor: '#0b2234',
      hoverRowColor: '#0e283d',
      textColor: '#e8f2fb',
      buttonBorderColor: '#24608c',
      buttonTextColor: '#23d9bd',
      buttonBGColor: '#081a29',
      buttonHoverBGColor: '#0e2d43',
      buttonHoverBorderColor: '#22d3ee',
      headerBGColor: '#0d3c44',
      headerTextColor: '#b7fff2',
      mutedTextColor: '#a4b7c9',
      primaryButtonBGColor: '#23d9bd',
      primaryButtonTextColor: '#071421',
      offlineActionBGColor: '#0d2d36',
      dangerTextColor: '#ff9c9c',
    },
    settingsDialog: {
      contentBG: '#071421',
      footerBG: '#0b1b2a',
    },
  },
}

export const mainColors = {
  light: {
    primary: '#00796f',
    secondary: '#00796f',
    surface: '#ffffff',
    contrastText: '#ffffff',
    labels: rgba('#0f172a', 0.9),
  },
  dark: {
    primary: '#23d9bd',
    secondary: '#23d9bd',
    surface: '#071421',
    contrastText: '#071421',
    labels: rgba('#e8f2fb', 0.95),
  },
}
